# Generated by Django 5.1.6 on 2025-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authorprofile",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="authorprofile",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
