# Generated by Django 5.1.6 on 2025-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_authorprofile_age_authorprofile_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
